name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] 
  workflow_dispatch:  

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FTHGL
          template: classic
          config_timezone: Europe/Istanbul

          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_achievements: yes
          plugin_traffic: yes
